package zgc.myrun.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import zgc.myrun.db.bean.LoginInfo;
import zgc.myrun.db.bean.Note;

import zgc.myrun.db.dao.LoginInfoDao;
import zgc.myrun.db.dao.NoteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteDaoConfig;
    private final DaoConfig loginInfoDaoConfig;
    private final NoteDao noteDao;
    private final LoginInfoDao loginInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        loginInfoDaoConfig = daoConfigMap.get(LoginInfoDao.class).clone();
        noteDaoConfig.initIdentityScope(type);
        loginInfoDaoConfig.initIdentityScope(type);

        noteDao = new NoteDao(noteDaoConfig, this);

        loginInfoDao = new LoginInfoDao(loginInfoDaoConfig,this);
        registerDao(Note.class, noteDao);
        registerDao(LoginInfo.class, loginInfoDao);
    }
    
    public void clear() {
        noteDaoConfig.getIdentityScope().clear();
        loginInfoDaoConfig.getIdentityScope().clear();
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }
    public LoginInfoDao getLoginInfoDao() {
        return loginInfoDao;
    }
}
