package zgc.myrun.db.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LOGIN_INFO".
 */
public class LoginInfo {

    private Long id;
    /** Not-null value. */
    private String Phone;
    /** Not-null value. */
    private String NickName;
    /** Not-null value. */
    private String Password;
    private java.util.Date Birthday;
    private String Sex;

    public LoginInfo() {
    }

    public LoginInfo(Long id) {
        this.id = id;
    }

    public LoginInfo(Long id, String Phone, String NickName, String Password, java.util.Date Birthday, String Sex) {
        this.id = id;
        this.Phone = Phone;
        this.NickName = NickName;
        this.Password = Password;
        this.Birthday = Birthday;
        this.Sex = Sex;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPhone() {
        return Phone;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPhone(String Phone) {
        this.Phone = Phone;
    }

    /** Not-null value. */
    public String getNickName() {
        return NickName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNickName(String NickName) {
        this.NickName = NickName;
    }

    /** Not-null value. */
    public String getPassword() {
        return Password;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPassword(String Password) {
        this.Password = Password;
    }

    public java.util.Date getBirthday() {
        return Birthday;
    }

    public void setBirthday(java.util.Date Birthday) {
        this.Birthday = Birthday;
    }

    public String getSex() {
        return Sex;
    }

    public void setSex(String Sex) {
        this.Sex = Sex;
    }

}
