package zgc.myrun.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RUN_RECORD".
 */
public class RunRecord {

    private Long id;
    /** Not-null value. */
    private String LonginName;
    /** Not-null value. */
    private java.util.Date RunDate;
    private java.util.Date StartTime;
    private java.util.Date EndTime;
    private Long StepNumber;
    private Long StepFrequercy;
    private Float RunDistance;
    private String RunShoes;
    private Float AverageSpeed;
    private Float FastestSpeed;
    private Float SlowestSpeed;

    public RunRecord() {
    }

    public RunRecord(Long id) {
        this.id = id;
    }

    public RunRecord(Long id, String LonginName, java.util.Date RunDate, java.util.Date StartTime, java.util.Date EndTime, Long StepNumber, Long StepFrequercy, Float RunDistance, String RunShoes, Float AverageSpeed, Float FastestSpeed, Float SlowestSpeed) {
        this.id = id;
        this.LonginName = LonginName;
        this.RunDate = RunDate;
        this.StartTime = StartTime;
        this.EndTime = EndTime;
        this.StepNumber = StepNumber;
        this.StepFrequercy = StepFrequercy;
        this.RunDistance = RunDistance;
        this.RunShoes = RunShoes;
        this.AverageSpeed = AverageSpeed;
        this.FastestSpeed = FastestSpeed;
        this.SlowestSpeed = SlowestSpeed;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getLonginName() {
        return LonginName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLonginName(String LonginName) {
        this.LonginName = LonginName;
    }

    /** Not-null value. */
    public java.util.Date getRunDate() {
        return RunDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRunDate(java.util.Date RunDate) {
        this.RunDate = RunDate;
    }

    public java.util.Date getStartTime() {
        return StartTime;
    }

    public void setStartTime(java.util.Date StartTime) {
        this.StartTime = StartTime;
    }

    public java.util.Date getEndTime() {
        return EndTime;
    }

    public void setEndTime(java.util.Date EndTime) {
        this.EndTime = EndTime;
    }

    public Long getStepNumber() {
        return StepNumber;
    }

    public void setStepNumber(Long StepNumber) {
        this.StepNumber = StepNumber;
    }

    public Long getStepFrequercy() {
        return StepFrequercy;
    }

    public void setStepFrequercy(Long StepFrequercy) {
        this.StepFrequercy = StepFrequercy;
    }

    public Float getRunDistance() {
        return RunDistance;
    }

    public void setRunDistance(Float RunDistance) {
        this.RunDistance = RunDistance;
    }

    public String getRunShoes() {
        return RunShoes;
    }

    public void setRunShoes(String RunShoes) {
        this.RunShoes = RunShoes;
    }

    public Float getAverageSpeed() {
        return AverageSpeed;
    }

    public void setAverageSpeed(Float AverageSpeed) {
        this.AverageSpeed = AverageSpeed;
    }

    public Float getFastestSpeed() {
        return FastestSpeed;
    }

    public void setFastestSpeed(Float FastestSpeed) {
        this.FastestSpeed = FastestSpeed;
    }

    public Float getSlowestSpeed() {
        return SlowestSpeed;
    }

    public void setSlowestSpeed(Float SlowestSpeed) {
        this.SlowestSpeed = SlowestSpeed;
    }

}
