package zgc.myrun.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RUN_RECORD_DETAIL".
 */
public class RunRecordDetail {

    private Long id;
    /** Not-null value. */
    private String LonginName;
    /** Not-null value. */
    private java.util.Date RunTiming;
    private String RunID;
    private String Position;
    private Float Longitude;
    private Float Latitude;
    private Float RunDistance;
    private Float AverageSpeed;
    private Long StepNumber;

    public RunRecordDetail() {
    }

    public RunRecordDetail(Long id) {
        this.id = id;
    }

    public RunRecordDetail(Long id, String LonginName, java.util.Date RunTiming, String RunID, String Position, Float Longitude, Float Latitude, Float RunDistance, Float AverageSpeed, Long StepNumber) {
        this.id = id;
        this.LonginName = LonginName;
        this.RunTiming = RunTiming;
        this.RunID = RunID;
        this.Position = Position;
        this.Longitude = Longitude;
        this.Latitude = Latitude;
        this.RunDistance = RunDistance;
        this.AverageSpeed = AverageSpeed;
        this.StepNumber = StepNumber;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getLonginName() {
        return LonginName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLonginName(String LonginName) {
        this.LonginName = LonginName;
    }

    /** Not-null value. */
    public java.util.Date getRunTiming() {
        return RunTiming;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRunTiming(java.util.Date RunTiming) {
        this.RunTiming = RunTiming;
    }

    public String getRunID() {
        return RunID;
    }

    public void setRunID(String RunID) {
        this.RunID = RunID;
    }

    public String getPosition() {
        return Position;
    }

    public void setPosition(String Position) {
        this.Position = Position;
    }

    public Float getLongitude() {
        return Longitude;
    }

    public void setLongitude(Float Longitude) {
        this.Longitude = Longitude;
    }

    public Float getLatitude() {
        return Latitude;
    }

    public void setLatitude(Float Latitude) {
        this.Latitude = Latitude;
    }

    public Float getRunDistance() {
        return RunDistance;
    }

    public void setRunDistance(Float RunDistance) {
        this.RunDistance = RunDistance;
    }

    public Float getAverageSpeed() {
        return AverageSpeed;
    }

    public void setAverageSpeed(Float AverageSpeed) {
        this.AverageSpeed = AverageSpeed;
    }

    public Long getStepNumber() {
        return StepNumber;
    }

    public void setStepNumber(Long StepNumber) {
        this.StepNumber = StepNumber;
    }

}
