package zgc.myrun.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import zgc.myrun.bean.RunRecord;
import zgc.myrun.bean.RunRecordDetail;
import zgc.myrun.bean.LoginInfo;

import zgc.myrun.dao.RunRecordDao;
import zgc.myrun.dao.RunRecordDetailDao;
import zgc.myrun.dao.LoginInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig runRecordDaoConfig;
    private final DaoConfig runRecordDetailDaoConfig;
    private final DaoConfig loginInfoDaoConfig;

    private final RunRecordDao runRecordDao;
    private final RunRecordDetailDao runRecordDetailDao;
    private final LoginInfoDao loginInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        runRecordDaoConfig = daoConfigMap.get(RunRecordDao.class).clone();
        runRecordDaoConfig.initIdentityScope(type);

        runRecordDetailDaoConfig = daoConfigMap.get(RunRecordDetailDao.class).clone();
        runRecordDetailDaoConfig.initIdentityScope(type);

        loginInfoDaoConfig = daoConfigMap.get(LoginInfoDao.class).clone();
        loginInfoDaoConfig.initIdentityScope(type);

        runRecordDao = new RunRecordDao(runRecordDaoConfig, this);
        runRecordDetailDao = new RunRecordDetailDao(runRecordDetailDaoConfig, this);
        loginInfoDao = new LoginInfoDao(loginInfoDaoConfig, this);

        registerDao(RunRecord.class, runRecordDao);
        registerDao(RunRecordDetail.class, runRecordDetailDao);
        registerDao(LoginInfo.class, loginInfoDao);
    }
    
    public void clear() {
        runRecordDaoConfig.getIdentityScope().clear();
        runRecordDetailDaoConfig.getIdentityScope().clear();
        loginInfoDaoConfig.getIdentityScope().clear();
    }

    public RunRecordDao getRunRecordDao() {
        return runRecordDao;
    }

    public RunRecordDetailDao getRunRecordDetailDao() {
        return runRecordDetailDao;
    }

    public LoginInfoDao getLoginInfoDao() {
        return loginInfoDao;
    }

}
